version: "3"

services:
   calendars:
     image: "registry.arkhotech.space/calendars"
     networks:
       - backend
     volumes:
       - ${CODE}:/var/www/html
     build:
       context: .
       dockerfile: phpfpm.dockerfile 
      
   cal_database:
       image: "mysql:5.5"
       volumes:
         -  database:/var/lib/mysql
         -  ./sql:/sql
         -  ./db-init.sh:/db-init.sh
       ports:
         - "3306:3306"
       environment:
         - MYSQL_ROOT_PASSWORD=calendar0293
       networks:
         - backend
       deploy:
         replicas: 1
   calnginx:
       image: "registry.arkhotech.space/nginx"
       ports:
         - "8090:80"
       volumes:
         - ./assets/nginx.conf:/etc/nginx/nginx.conf
         - ${CODE}:/var/www/html
       depends_on:
         - calendars
       networks:
         - frontend
         - backend

volumes:
  redisdata:
  database:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
